databases:
  - name: passa_cola
    plan: free
    databaseName: avaliacoes  # Nome do seu banco de dados MySQL
    user: root  # Nome de usuário do banco de dados MySQL
    type: mysql  # Tipo de banco de dados

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        value: mysql://root:juliana@localhost:3306/avaliacoes
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4