# Generated by Django 5.0.6 on 2024-05-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliacao',
            field=models.CharField(max_length=1000),
        ),
    ]
