# Generated by Django 5.0.6 on 2024-05-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_materias', '0002_alter_avaliacao_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliacao',
            field=models.CharField(max_length=3000),
        ),
    ]
